#!/usr/bin/env bash

status=$(cat /sys/class/power_supply/BAT{0,1}/status | grep -c "Discharging")
if [ "$status" -gt 0 ]; then
    bat0=$(awk '{print $1*10^-6}' /sys/class/power_supply/BAT0/power_now)
    bat1=$(awk '{print $1*10^-6}' /sys/class/power_supply/BAT1/power_now)
    total=$(echo "$bat0 + $bat1" | bc)
    echo "$total W"
else
    echo "0 W"
fi

