#!/usr/bin/env bash
bar_icon=""

while true; do
    if (ping -c 1 github.com || ping -c 1 bitbucket.org || ping -c 1 opensuse.org) &>/dev/null; then
        updates=$(zypper lu | grep 'v ' | wc -l)
        echo "$bar_icon $updates"
    else
        echo "$bar_icon Error"
    fi;
    sleep 3600
done
