#!/usr/bin/env bash
while true; do
    if (ping -c 1 github.com || ping -c 1 bitbucket.org || ping -c 1 opensuse.org) &>/dev/null; then
        updates=$(zypper lu | grep 'v ' | wc -l)
        echo "$updates"
    else
        echo "Error"
    fi;
    sleep 3600
done
